### ISSUE TITLE
Provider fails booting due connection failure

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/docker-images#34]
## Expected Behavior

Whole thing up and running.

## Current Behavior

Provider shuts down due failure to connect to keeper-contracts

## Failure Information (for bugs)

Looks like provider fails to connect to keeper contracts. Check the log from below.

## Step to Reproduce the problem

1. Clone repository
2. Run "./start_ocean.sh"
3. Observe provider logs

### Possible Solution

Hostname from ENV variable

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Docker: 18.06.1-ce
* Node: v8.11.3
* OS: macOS

## Failure Logs

```
keeper-contracts_1  | Listening on 0.0.0.0:8545
keeper-contracts_1  | Compiling ./contracts/Migrations.sol...
keeper-contracts_1  | Compiling ./contracts/OceanMarket.sol...
keeper-contracts_1  | Compiling ./contracts/auth/OceanAuth.sol...
keeper-contracts_1  | Compiling ./contracts/dispute/OceanDispute.sol...
keeper-contracts_1  | Compiling ./contracts/plcrvoting/AttributeStore.sol...
keeper-contracts_1  | Compiling ./contracts/plcrvoting/DLL.sol...
keeper-contracts_1  | Compiling ./contracts/plcrvoting/PLCRVoting.sol...
keeper-contracts_1  | Compiling ./contracts/tcr/OceanRegistry.sol...
keeper-contracts_1  | Compiling ./contracts/token/OceanToken.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
keeper-contracts_1  | Compiling openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol...
keeper-contracts_1  | Writing artifacts to ./build/contracts
keeper-contracts_1  | 
provider_1          | [2018-10-18 12:34:48 +0000] [7] [INFO] Starting gunicorn 19.9.0
provider_1          | [2018-10-18 12:34:48 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
provider_1          | [2018-10-18 12:34:48 +0000] [7] [INFO] Using worker: sync
provider_1          | [2018-10-18 12:34:48 +0000] [9] [INFO] Booting worker with pid: 9
keeper-contracts_1  | net_version
keeper-contracts_1  | eth_accounts
keeper-contracts_1  | Using network 'development'.
keeper-contracts_1  | 
keeper-contracts_1  | Running migration: 1_initial_migration.js
keeper-contracts_1  | eth_accounts
keeper-contracts_1  | net_version
keeper-contracts_1  |   Deploying Migrations...
keeper-contracts_1  | net_version
keeper-contracts_1  | eth_sendTransaction
keeper-contracts_1  |   ... 0xf2db8d9e6a0587f0a4e4e8ff12a98208751657f369cb7f2e69f50d2b538fa997
keeper-contracts_1  | eth_newBlockFilter
keeper-contracts_1  | eth_getFilterChanges
keeper-contracts_1  | eth_getTransactionReceipt
provider_1          | [2018-10-18 12:34:49 +0000] [9] [ERROR] Exception in worker process
provider_1          | Traceback (most recent call last):
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
provider_1          |     (self._dns_host, self.port), self.timeout, **extra_kw)
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
provider_1          |     raise err
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
provider_1          |     sock.connect(sa)
provider_1          | ConnectionRefusedError: [Errno 111] Connection refused
provider_1          | 
provider_1          | During handling of the above exception, another exception occurred:
provider_1          | 
provider_1          | Traceback (most recent call last):
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
provider_1          |     chunked=chunked)
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
provider_1          |     conn.request(method, url, **httplib_request_kw)
provider_1          |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
provider_1          |     self._send_request(method, url, body, headers, encode_chunked)
provider_1          |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
provider_1          |     self.endheaders(body, encode_chunked=encode_chunked)
provider_1          |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
provider_1          |     self._send_output(message_body, encode_chunked=encode_chunked)
provider_1          |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
provider_1          |     self.send(msg)
provider_1          |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
provider_1          |     self.connect()
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
provider_1          |     conn = self._new_conn()
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
provider_1          |     self, "Failed to establish a new connection: %s" % e)
provider_1          | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faf56c105f8>: Failed to establish a new connection: [Errno 111] Connection refused
provider_1          | 
provider_1          | During handling of the above exception, another exception occurred:
provider_1          | 
provider_1          | Traceback (most recent call last):
provider_1          |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
provider_1          |     timeout=timeout
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
provider_1          |     _stacktrace=sys.exc_info()[2])
provider_1          |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
provider_1          |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
provider_1          | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf56c105f8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by jernejpregelj** [comment]
Working now with --latest flag
