### ISSUE TITLE
Aquarius fails to boot

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/docker-images#83]
upon `./start_ocean.sh --no-pleuston --local-spree-node --no-brizo`

```
[2018-12-15 19:27:44 +0000] [8] [INFO] Starting gunicorn 19.9.0
[2018-12-15 19:27:44 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
[2018-12-15 19:27:44 +0000] [8] [INFO] Using worker: sync
[2018-12-15 19:27:44 +0000] [10] [INFO] Booting worker with pid: 10
[2018-12-15 19:27:45 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/provider/provider/run.py", line 27, in <module>
    from provider.app.assets import assets
  File "/provider/provider/app/assets.py", line 18, in <module>
    dao = Dao(config_file)
  File "/provider/provider/app/dao.py", line 7, in __init__
    self.oceandb = OceanDb(config_file).plugin
  File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/oceandb.py", line 19, in __init__
    self.plugin = start_plugin(file_path)
  File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 37, in start_plugin
    plugin_instance = load_plugin(config)
  File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 65, in load_plugin
    return mod.Plugin(config)
TypeError: Can't instantiate abstract class Plugin with abstract methods text_query
```

**Comment by diminator** [comment]
This might be an issue in `oceandb_driver_interface` or `aquarius` @eruizgar91

**Comment by diminator** [comment]
solved by using the `latest` flag
